# **Lists**

Q1. Create a list of 5 random numbers and print the list.

In [2]:
num=[10,20,30,40,50]
print("Numbers list:",num)

Numbers list: [10, 20, 30, 40, 50]

Q2. Insert 3 new values to the list and print the updated list.

In [7]:
num=[10,20,30,40,50]
num[5:7]=[60,70,80]
print("Updated List:",num)

Updated List: [10, 20, 30, 40, 50, 60, 70, 80]

Q3. Try to use a for loop to print each element in the list.

In [8]:
num=[10,20,30,40,50,60,70,80]
for i in num:
  print(i)

10
20
30
40
50
60
70
80

# **Dictionary**

Q1.Create a dictionary with keys 'name', 'age', and 'address' and values 'John', 25, and 'New York' respectively.

In [9]:
Details={"Name":"John",
         "Age":25,
         "Address":"New York"}
print("Details_Dictionary:",Details)

Details_Dictionary: {'Name': 'John', 'Age': 25, 'Address': 'New York'}

Q2. Add a new key-value pair to the dictionary created in Q1 with key 'phone' and value '1234567890'.

In [10]:
Details['Phone']=1234567890
print("Updated Details:",Details)

Updated Details: {'Name': 'John', 'Age': 25, 'Address': 'New York', 'Phone': 1234567890}

# **Set**

Q1.Create a set with values 1, 2, 3, 4, and 5.

In [2]:
number_sets={1,2,3,4,5}
print("Numbers_set:",number_sets)

Numbers_set: {1, 2, 3, 4, 5}

Q2. Add the value 6 to the set created in Q1.

In [3]:
number_sets={1,2,3,4,5}
number_sets.add(6)
print("Updated Numbers_set:",number_sets)

Updated Numbers_set: {1, 2, 3, 4, 5, 6}

Q3. Remove the value 3 from the set created in Q1.

In [4]:
number_sets={1,2,3,4,5,6}
number_sets.remove(3)
print("Updated numbers_set:",number_sets)

Updated numbers_set: {1, 2, 4, 5, 6}

# **Tuple**

Q1. Create a tuple with values 1, 2, 3, and 4

In [5]:
T1=(1,2,3,4)
print(type(T1))
print("Tuple:",T1)

<class 'tuple'>
Tuple: (1, 2, 3, 4)

Q2. Print the length of the tuple created in Q1.

In [6]:
T1=(1,2,3,4)
length=len(T1)
print("Length of the tuple:",length)

Length of the tuple: 4